# --from-source (plan 2026-09-27-v1-dist, Task 11, spec §6.2). Sourced by harness.sh.
# shellcheck shell=sh
# shellcheck disable=SC2034 # RC, TH and the like are read by harness.sh's helpers

FS_GIT_ID="-c user.name=fromsource-test -c user.email=fromsource-test@example.invalid -c commit.gpgsign=false"

# fs_scaffold DIR VERSION VERDANDI_URL VERDANDI_REV: a minimal but real eitri-shaped checkout --
# just enough for checkout_version, lockfile_rev and agent_toml_verdandi to read something real, and
# for from_source_stage to find real files at the paths it copies (the launcher, the desktop entry,
# this installer itself, LICENSE). Not committed yet -- the caller commits and tags.
fs_scaffold() {
	_fs_dir=$1
	rm -rf "$_fs_dir"
	mkdir -p "$_fs_dir/shell" "$_fs_dir/agent" "$_fs_dir/packaging"
	# The real tree's own shape (Task 1, D1): shell/Cargo.toml names `version.workspace = true`, not
	# a plain quoted string, and the version itself lives once in the root's [workspace.package]
	# (installer-codex-2: checkout_version used to die against exactly this shape).
	{
		printf '[workspace]\n'
		printf 'resolver = "2"\n'
		printf 'members = ["shell", "agent"]\n'
		printf '\n[workspace.package]\n'
		printf 'version = "%s"\n' "$2"
		printf 'edition = "2021"\n'
	} >"$_fs_dir/Cargo.toml"
	{
		printf '[package]\n'
		printf 'name = "shell"\n'
		printf 'version.workspace = true\n'
		printf 'edition.workspace = true\n'
	} >"$_fs_dir/shell/Cargo.toml"
	{
		printf '[package]\n'
		printf 'name = "agent"\n'
		printf 'version = "%s"\n' "$2"
		printf 'edition.workspace = true\n'
		printf '\n[dependencies]\n'
		printf 'claude-runtime-protocol = { git = "%s", rev = "%s" }\n' "$3" "$4"
	} >"$_fs_dir/agent/Cargo.toml"
	{
		printf '# This file is automatically @generated by Cargo.\nversion = 3\n\n'
		printf '[[package]]\n'
		printf 'name = "neovide"\n'
		printf 'version = "0.1.0"\n'
		printf 'source = "git+https://example.invalid/neovide.git?rev=%s#%s"\n' "$FS_FORK_REV" "$FS_FORK_REV"
	} >"$_fs_dir/Cargo.lock"
	{
		printf 'NODE_VERSION=%s\n' "$NODE_FIXTURE_VERSION"
		printf 'NODE_SHA256_linux_x64=%s\n' "$NODE_FIXTURE_SHA256_X64"
		printf 'NODE_SHA256_linux_arm64=%s\n' "$NODE_FIXTURE_SHA256_ARM64"
		printf 'NVIM_VERSION=%s\n' "$NVIM_FIXTURE_VERSION"
		printf 'NVIM_SHA256_linux_x86_64=%s\n' "$NVIM_FIXTURE_SHA256"
		printf 'SKIA_BINARIES_URL_UPSTREAM=%s\n' "$SKIA_FIXTURE_URL"
		printf 'SKIA_BINARIES_SHA256=%s\n' "$SKIA_FIXTURE_SHA256"
	} >"$_fs_dir/packaging/pins.env"
	cp "$PKG/eitri.launcher.sh" "$_fs_dir/packaging/eitri.launcher.sh"
	cp "$PKG/cn.huntergrey.eitri.desktop" "$_fs_dir/packaging/cn.huntergrey.eitri.desktop"
	cp "$PKG/cn.huntergrey.eitri.Panel.desktop" "$_fs_dir/packaging/cn.huntergrey.eitri.Panel.desktop"
	mkdir -p "$_fs_dir/nvim"
	cp -R "$PKG/../nvim/eitri.nvim" "$_fs_dir/nvim/eitri.nvim"
	cp -R "$PKG/../gnome-extension" "$_fs_dir/gnome-extension"
	cp -R "$PKG/icons" "$_fs_dir/packaging/icons"
	cp "$INSTALLER" "$_fs_dir/packaging/install.sh"
	printf 'test fixture LICENSE: MIT-shaped, not the real text.\n' >"$_fs_dir/LICENSE"
}

# fs_commit_and_tag DIR VERSION: sets FS_HEAD to the real commit sha.
fs_commit_and_tag() {
	# shellcheck disable=SC2086 # FS_GIT_ID is deliberately several words
	git -C "$1" init -q
	# shellcheck disable=SC2086
	git -C "$1" $FS_GIT_ID add -A
	# shellcheck disable=SC2086
	git -C "$1" $FS_GIT_ID commit -q -m base
	git -C "$1" tag "v$2"
	FS_HEAD=$(git -C "$1" rev-parse HEAD)
}

# fs_repo VERSION VERDANDI_URL VERDANDI_REV: fs_scaffold + fs_commit_and_tag under $T, once per
# call. Sets FS_DIR and FS_HEAD.
fs_repo() {
	FS_DIR=$T/fs-repo
	fs_scaffold "$FS_DIR" "$1" "$2" "$3"
	fs_commit_and_tag "$FS_DIR" "$1"
}

# fs_verdandi_checkout DIR: a minimal but real Verdandi checkout (like mk_verdandi_source, but a
# real git working tree, for --verdandi-checkout's own rev/status checks). Sets FS_VC_HEAD.
fs_verdandi_checkout() {
	_fvc=$1
	rm -rf "$_fvc"
	mkdir -p "$_fvc/apps/claude-sidecar/scripts"
	printf '{\n  "name": "verdandi",\n  "private": true\n}\n' >"$_fvc/package.json"
	printf '{\n  "name": "@verdandi/claude-sidecar",\n  "version": "0.1.0"\n}\n' >"$_fvc/apps/claude-sidecar/package.json"
	printf '// test fixture: never run\n' >"$_fvc/apps/claude-sidecar/scripts/buildBinary.mjs"
	# shellcheck disable=SC2086
	git -C "$_fvc" init -q
	# shellcheck disable=SC2086
	git -C "$_fvc" $FS_GIT_ID add -A
	# shellcheck disable=SC2086
	git -C "$_fvc" $FS_GIT_ID commit -q -m base
	FS_VC_HEAD=$(git -C "$_fvc" rev-parse HEAD)
}

# mk_from_source_release VERSION REV COMMIT: mk_release (the shared harness fixture builder), with
# its own always-fake EITRI_COMMIT replaced by COMMIT (a from-source fixture repo's real HEAD) and
# re-signed. A fresh VERSION every caller uses (9.9.x), never one of setup_releases' own 1.x.y
# versions: mutating those in place would corrupt every other test file's shared fixtures.
mk_from_source_release() {
	mk_release "$1" "$2"
	sed -i "s/^EITRI_COMMIT=.*/EITRI_COMMIT=$3/" "$S/fix/v$1/RELEASE"
	resign "$S/fix/v$1"
}

# fs_cargo_stubs: PRE_STUBS-ready directory holding the recording cargo stub (fixtures/cargo-fromsource,
# shared: harness.sh's own setup_stubs built it once, under $S itself, as $S/stubs-cargo -- its own
# `S=$(cd "$(dirname "$0")/.." && pwd)` only resolves to the real $S from a directory one level under
# it) under the name `cargo`, and nothing else -- $S/stubs (right after it) still supplies the
# forbidden commands and claude, and /usr/bin:/bin (the default path-tail, right after that) supplies
# the real rustc/cc/pkg-config/protoc/git check_build_tools also needs, none of which any test here
# stubs.
fs_cargo_stubs() { printf '%s\n' "$S/stubs-cargo"; }

# ---------------------------------------------------------------------------------------------
# --from-source without --checkout (spec §6.2)

TESTS="$TESTS t_from_source_clone_head_mismatch_refuses"
t_from_source_clone_head_mismatch_refuses() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_repo 9.9.1 https://github.com/HunterGrey-cyber/verdandi.git ddddddd000000000000000000000000000000000
	# setup_releases' own mk_release always writes EITRI_COMMIT=1111...1, which is never a real
	# git repo's HEAD -- so the clone this checks against never matches.
	mk_release 9.9.1 ddddddd000000000000000000000000000000000
	serve 9.9.1
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_REPO_URL=$FS_DIR" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		-- --from-source --version 9.9.1 --base-url "http://127.0.0.1:$PORT" --release-signers "$SIGNERS"
	expect_rc 1
	if ! grep -Fq "is at $FS_HEAD, not 1111111111111111111111111111111111111111" "$OUT"; then
		fail "the clone-mismatch message does not name both commits: $(cat "$OUT")"
	fi
	if grep -q '^cargo build ' "$S/logs/cargo.log"; then fail "cargo build ran despite the clone mismatch"; fi
}

TESTS="$TESTS t_from_source_clone_head_match_builds_and_installs"
t_from_source_clone_head_match_builds_and_installs() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_repo 9.9.2 https://github.com/HunterGrey-cyber/verdandi.git ddddddd000000000000000000000000000000000
	mk_from_source_release 9.9.2 ddddddd000000000000000000000000000000000 "$FS_HEAD"
	serve 9.9.2
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_REPO_URL=$FS_DIR" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --version 9.9.2 --base-url "http://127.0.0.1:$PORT" --release-signers "$SIGNERS"
	expect_rc 0
	expect_out "building Eitri 9.9.2 from source"
	if [ "$(grep -c '^cargo build ' "$S/logs/cargo.log")" != 1 ]; then
		fail "cargo build did not run exactly once: $(cat "$S/logs/cargo.log")"
	fi
	# F3 (v1-dist whole-branch review, 2026-09-28): --target-dir now pins staging's own
	# <src>/target/release assumption -- $TH/.cache/eitri/src is clone_public_eitri's own
	# NV_CACHE_NV/src, the from-source dir a network (non---checkout) build clones into.
	if ! grep -Fqx "cargo build --release --locked --target-dir $TH/.cache/eitri/src/target -p shell -p agent -p supervisor --bins" "$S/logs/cargo.log"; then
		fail "the recorded build command is not exactly the spec's: $(cat "$S/logs/cargo.log")"
	fi
	# Installed exactly like the prebuilt path: the four binaries, the launcher, RELEASE, licences.
	for b in shell eitri-supervisor eitri-tmux-shim eitri-claude-handoff; do
		expect_exec "$TH/.local/lib/eitri/$b"
	done
	expect_exec "$TH/.local/bin/eitri"
	expect_file "$TH/.local/lib/eitri/RELEASE"
	expect_eq "$(installed_version)" 9.9.2 "the version installed from source"
	for f in LICENSE THIRD-PARTY-LICENSES SOURCE; do
		expect_file "$TH/.local/share/licenses/eitri/$f"
	done
	if ! grep -q 'built directly from source' "$TH/.local/share/licenses/eitri/THIRD-PARTY-LICENSES"; then
		fail "THIRD-PARTY-LICENSES does not say it is a from-source placeholder"
	fi
	# The desktop entry named by the application id, and the icon, from the checkout's packaging/; the
	# placeholder licence file carries the logo's CC BY notice, which needs no generating.
	expect_file "$(data_of)/applications/cn.huntergrey.eitri.desktop"
	expect_file "$(data_of)/applications/cn.huntergrey.eitri.Panel.desktop"
	for f in plugin/eitri.lua lua/eitri/init.lua doc/eitri.txt; do
		if ! cmp -s "$PKG/../nvim/eitri.nvim/$f" "$(data_of)/eitri/eitri.nvim/$f"; then fail "the plugin file $f was not installed from the checkout"; fi
	done
	for f in metadata.json extension.js direction.js policy.js; do
		if ! cmp -s "$PKG/../gnome-extension/$f" "$(data_of)/gnome-shell/extensions/eitri@huntergrey.cn/$f"; then fail "the extension file $f was not installed from the checkout"; fi
	done
	expect_absent "$(data_of)/applications/eitri.desktop"
	for f in $(cd "$PKG/icons" && find hicolor -type f | LC_ALL=C sort); do
		if ! cmp -s "$PKG/icons/$f" "$(data_of)/icons/$f"; then fail "the icon $f was not installed from the checkout"; fi
	done
	if ! grep -Fq "$(cat "$PKG/icons/LICENSE")" "$TH/.local/share/licenses/eitri/THIRD-PARTY-LICENSES"; then
		fail "THIRD-PARTY-LICENSES lacks the logo's licence notice"
	fi
}

TESTS="$TESTS t_from_source_node_checksum_verified_before_build"
t_from_source_node_checksum_verified_before_build() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_repo 9.9.3 https://github.com/HunterGrey-cyber/verdandi.git ddddddd000000000000000000000000000000000
	mk_from_source_release 9.9.3 ddddddd000000000000000000000000000000000 "$FS_HEAD"
	serve 9.9.3
	PRE_STUBS=$(fs_cargo_stubs)
	# A corrupt Node tarball at the exact path sidecar_download_node fetches (dist/vX/node-...).
	_bad=$S/srv/dist/$NODE_FIXTURE_VERSION/node-$NODE_FIXTURE_VERSION-linux-x64.tar.xz
	cp "$_bad" "$T/good-node.tar.xz"
	echo corrupt >"$_bad"
	inst --set "EITRI_INSTALL_TEST_REPO_URL=$FS_DIR" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		-- --from-source --version 9.9.3 --base-url "http://127.0.0.1:$PORT" --release-signers "$SIGNERS"
	expect_rc 1
	expect_out "checksum mismatch for node-$NODE_FIXTURE_VERSION-linux-x64.tar.xz"
	if grep -q '^cargo build ' "$S/logs/cargo.log"; then fail "cargo build ran despite the Node checksum mismatch"; fi
	cp "$T/good-node.tar.xz" "$_bad"
}

TESTS="$TESTS t_from_source_missing_build_tools_refuses"
t_from_source_missing_build_tools_refuses() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_repo 9.9.4 https://github.com/HunterGrey-cyber/verdandi.git ddddddd000000000000000000000000000000000
	mk_from_source_release 9.9.4 ddddddd000000000000000000000000000000000 "$FS_HEAD"
	serve 9.9.4
	inst --path-tail "$S/path-no-cargo" \
		--set "EITRI_INSTALL_TEST_REPO_URL=$FS_DIR" \
		-- --from-source --version 9.9.4 --base-url "http://127.0.0.1:$PORT" --release-signers "$SIGNERS"
	expect_rc 1
	expect_out "building from source needs cargo and rustc"
	expect_out 'sudo apt install build-essential clang pkg-config libgtk-4-dev libwebkitgtk-6.0-dev protobuf-compiler git'
}

TESTS="$TESTS t_from_source_dry_run_refuses"
t_from_source_dry_run_refuses() {
	inst -- --from-source --dry-run
	expect_rc 1
	expect_out '--dry-run is not supported with --from-source'
}

TESTS="$TESTS t_from_source_tarball_option_conflict_refuses"
t_from_source_tarball_option_conflict_refuses() {
	inst -- --from-source --tarball x --sums y
	expect_rc 1
	expect_out 'Use one or the other'
}

# F2 (v1-dist whole-branch review, 2026-09-28): semver_cmp's downgrade refusal used to be called
# only from do_install -- --from-source never refused a downgrade at all, so a mirror serving an
# older, genuinely signed release rolled a from-source user silently backward, which is exactly the
# rollback case spec §6.4 says a signature does not cover.
TESTS="$TESTS t_from_source_older_version_refused"
t_from_source_older_version_refused() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_repo 9.9.10 https://github.com/HunterGrey-cyber/verdandi.git ddddddd000000000000000000000000000000000
	mk_from_source_release 9.9.10 ddddddd000000000000000000000000000000000 "$FS_HEAD"
	serve 9.9.10
	# The installed version comes from a plain prebuilt install -- a from-source build's own output
	# is installed the same way as a tarball's (finish_install), so this is a faithful "already
	# installed" starting point.
	inst_net --version 9.9.10
	expect_rc 0
	expect_eq "$(installed_version)" 9.9.10

	fs_repo 9.9.9 https://github.com/HunterGrey-cyber/verdandi.git ddddddd000000000000000000000000000000000
	mk_from_source_release 9.9.9 ddddddd000000000000000000000000000000000 "$FS_HEAD"
	serve 9.9.9 9.9.10
	before=$(snap "$TH")
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_REPO_URL=$FS_DIR" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		-- --from-source --base-url "http://127.0.0.1:$PORT" --release-signers "$SIGNERS"
	expect_fail "a from-source downgrade without --version"
	expect_out 'Eitri 9.9.10 is installed, and the release offered is older (9.9.9): refusing to downgrade silently'
	expect_out '--version 9.9.9'
	expect_eq "$(snap "$TH")" "$before" "the home after a refused from-source downgrade"
	if [ -f "$S/logs/cargo.log" ] && grep -q '^cargo build ' "$S/logs/cargo.log"; then
		fail "cargo build ran despite the downgrade refusal: $(cat "$S/logs/cargo.log")"
	fi

	# With --version, the refusal does not apply: the run proceeds to a real clone-and-build.
	inst --set "EITRI_INSTALL_TEST_REPO_URL=$FS_DIR" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --version 9.9.9 --base-url "http://127.0.0.1:$PORT" --release-signers "$SIGNERS"
	expect_rc 0
	expect_eq "$(installed_version)" 9.9.9 "the explicit from-source downgrade"
}

# ---------------------------------------------------------------------------------------------
# --from-source --checkout DIR (spec §6.2, D11's own dev loop)

TESTS="$TESTS t_from_source_checkout_public_rev_builds_and_installs"
t_from_source_checkout_public_rev_builds_and_installs() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	# The pinned rev must be one resolve_verdandi_source's own public-clone branch can actually
	# check out: a fresh clone of EITRI_INSTALL_TEST_VERDANDI_REPO_URL (this fixture), not an
	# arbitrary 40-hex string.
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_VERDANDI_REPO_URL=$T/verdandi-src" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --checkout "$FS_DIR"
	expect_rc 0
	# F3 (v1-dist whole-branch review, 2026-09-28): --target-dir now pins staging's own
	# <src>/target/release assumption; for --checkout that src is $FS_DIR itself.
	if ! grep -Fqx "cargo build --release --locked --target-dir $FS_DIR/target -p shell -p agent -p supervisor --bins" "$S/logs/cargo.log"; then
		fail "the recorded build command is not exactly the spec's: $(cat "$S/logs/cargo.log")"
	fi
	if ! grep -Fqx "SKIA_BINARIES_URL=file://$T/home/.cache/eitri/from-source-skia/skia-binaries-test.tar.gz" "$S/logs/cargo.log"; then
		fail "the build did not see the pinned, checked local Skia archive: $(cat "$S/logs/cargo.log")"
	fi
	expect_exec "$TH/.local/lib/eitri/shell"
	expect_eq "$(installed_version)" 1.0.0 "the version installed from --checkout"
	have_rev=$(sed -n 's/^VERDANDI_REV=//p' "$TH/.local/lib/eitri/RELEASE")
	expect_eq "$have_rev" "$FS_VC_HEAD" "the synthesized RELEASE's own VERDANDI_REV"
	have_commit=$(sed -n 's/^EITRI_COMMIT=//p' "$TH/.local/lib/eitri/RELEASE")
	expect_eq "$have_commit" "$FS_HEAD" "the synthesized RELEASE's own EITRI_COMMIT"
	if ! grep -Fqx 'EITRI_BUILT_FROM_CHECKOUT=1' "$TH/.local/lib/eitri/RELEASE"; then
		fail "the installed RELEASE is not marked EITRI_BUILT_FROM_CHECKOUT: $(cat "$TH/.local/lib/eitri/RELEASE")"
	fi
}

TESTS="$TESTS t_from_source_checkout_from_before_the_app_icon_refuses_with_a_pointer"
t_from_source_checkout_from_before_the_app_icon_refuses_with_a_pointer() {
	# A source tree whose desktop entry is still packaging/eitri.desktop (no icons): this installer does
	# not lay it out, says so, and installs nothing.
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	mv "$FS_DIR/packaging/cn.huntergrey.eitri.desktop" "$FS_DIR/packaging/eitri.desktop"
	rm -rf "$FS_DIR/packaging/icons"
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_VERDANDI_REPO_URL=$T/verdandi-src" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --checkout "$FS_DIR"
	expect_fail "a source tree from before the app icon"
	expect_out 'is a source tree from before Eitri'"'"'s app icon'
	expect_out 'packaging/eitri.desktop'
	expect_out 'first run: eitri setup --uninstall (or, with this installer: sh install.sh --uninstall)'
	expect_out "then install that tree with its own packaging/install.sh --from-source"
	expect_absent "$TH/.local/lib/eitri"
	expect_absent "$(data_of)/applications/cn.huntergrey.eitri.desktop"
	expect_absent "$(data_of)/icons"
}

# F3 (v1-dist whole-branch review, 2026-09-28): from_source_stage always read <src>/target/release,
# but the build honoured the caller's own CARGO_TARGET_DIR -- a --checkout tree with an older
# target/release/shell already on disk (this project's own dev loop: ./install.sh run more than once
# against different pins, or simply a workspace someone had already built by hand) silently staged
# that STALE binary under a RELEASE naming the CURRENT HEAD, because a caller's CARGO_TARGET_DIR
# redirected the fresh build somewhere staging never looked.
TESTS="$TESTS t_from_source_checkout_target_dir_pinned_against_stale_binary"
t_from_source_checkout_target_dir_pinned_against_stale_binary() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	mkdir -p "$FS_DIR/target/release"
	printf '#!/bin/sh\necho "STALE stub shell: must never be installed"\n' >"$FS_DIR/target/release/shell"
	chmod 0755 "$FS_DIR/target/release/shell"
	_elsewhere=$T/elsewhere-cargo-target
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_VERDANDI_REPO_URL=$T/verdandi-src" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		--set "CARGO_TARGET_DIR=$_elsewhere" \
		-- --from-source --checkout "$FS_DIR"
	expect_rc 0
	# --target-dir wins over the caller's CARGO_TARGET_DIR (cargo's own precedence), so the stub
	# build's fresh binaries land at $FS_DIR/target/release, not $_elsewhere/release.
	if ! grep -Fqx "cargo build --release --locked --target-dir $FS_DIR/target -p shell -p agent -p supervisor --bins" "$S/logs/cargo.log"; then
		fail "--target-dir did not win over the caller's CARGO_TARGET_DIR: $(cat "$S/logs/cargo.log")"
	fi
	if grep -q 'STALE stub shell' "$TH/.local/lib/eitri/shell"; then
		fail "the stale planted binary was installed instead of a fresh build"
	fi
	if ! grep -q 'from-source test build' "$TH/.local/lib/eitri/shell"; then
		fail "the installed shell is not the fresh stub build: $(cat "$TH/.local/lib/eitri/shell")"
	fi
	# --target-dir wins entirely (real cargo's own precedence): the caller's CARGO_TARGET_DIR is
	# never touched at all.
	expect_absent "$_elsewhere"
}

# F3 fix-round-1 regression (v1-dist whole-branch review, fix round 2, 2026-09-28; [codex-t1-1]):
# NV_FROM_SOURCE_DIR used to stay exactly what --checkout was given. run_in cds into it before
# exec'ing cargo, but --target-dir's own value is expanded here, in the caller, before that cd ever
# happens -- so a relative --checkout resolved "$NV_FROM_SOURCE_DIR/target" against the ORIGINAL
# cwd (correct) everywhere except inside that one cargo argument, which then resolved a second time
# against the POST-cd cwd (the checkout itself), landing the real build one directory too deep. The
# pre-build rm loop (which runs outside run_in, so it still resolves correctly against the original
# cwd) had already deleted the one place staging looks, so what used to be a working invocation
# died with "did not produce target/release/shell" even though the build itself succeeded --
# reproduced here exactly as reported: --checkout given as a relative path, run from that checkout's
# own parent directory (which is where $T/cwd, this harness's fixed installer cwd, and $FS_DIR, a
# sibling of it under $T, put every test by construction).
TESTS="$TESTS t_from_source_checkout_relative_path_from_its_parent_directory"
t_from_source_checkout_relative_path_from_its_parent_directory() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_VERDANDI_REPO_URL=$T/verdandi-src" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --checkout ../fs-repo
	expect_rc 0
	# The absolutized checkout dir, not the literal relative argument: --target-dir must name the
	# same $FS_DIR/target a matching absolute --checkout would (the test right above this one).
	if ! grep -Fqx "cargo build --release --locked --target-dir $FS_DIR/target -p shell -p agent -p supervisor --bins" "$S/logs/cargo.log"; then
		fail "a relative --checkout did not resolve --target-dir against the checkout itself: $(cat "$S/logs/cargo.log")"
	fi
	expect_exec "$TH/.local/lib/eitri/shell"
	expect_eq "$(installed_version)" 1.0.0 "the version installed from a relative --checkout"
}

# F3 minor follow-up (v1-dist whole-branch review, fix round 2, 2026-09-28): nothing exercised the
# rm loop's own reason for existing -- a build that runs and exits 0 but writes nothing into
# <src>/target/release (redirected elsewhere by a caller's own cargo config, or genuinely skipped)
# used to leave staging free to pick up whatever binary was already on disk from an earlier run,
# under a RELEASE naming the CURRENT build. Planting a stale binary and using the cargo stub's
# "skip" mode (writes nothing at all) proves the rm loop is what turns that into an honest failure.
TESTS="$TESTS t_from_source_checkout_build_that_writes_nothing_refuses_stale_binary"
t_from_source_checkout_build_that_writes_nothing_refuses_stale_binary() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	mkdir -p "$FS_DIR/target/release"
	printf '#!/bin/sh\necho "STALE stub shell: must never be installed"\n' >"$FS_DIR/target/release/shell"
	chmod 0755 "$FS_DIR/target/release/shell"
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_VERDANDI_REPO_URL=$T/verdandi-src" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		--set "EITRI_INSTALL_TEST_CARGO_MODE=skip" \
		-- --from-source --checkout "$FS_DIR"
	expect_fail "a build that wrote nothing into target/release, with a stale binary already there"
	expect_out "the build did not produce target/release/shell"
	if [ -e "$TH/.local/lib/eitri/shell" ]; then
		fail "the stale planted binary was installed despite the build producing nothing"
	fi
	expect_absent "$TH/.local/lib/eitri"
	# The rm loop really did remove it (rather than the stub simply never having been asked to
	# overwrite it): the stale file is gone from the source tree too.
	expect_absent "$FS_DIR/target/release/shell"
}

TESTS="$TESTS t_from_source_checkout_setup_refuses_honestly_not_as_a_mismatch"
t_from_source_checkout_setup_refuses_honestly_not_as_a_mismatch() {
	# installer-claude-7: a --checkout install's own RELEASE names a VERDANDI_SOURCE_SHA256 that is
	# a `git archive` hash of the checkout tree, never the real release asset's bytes. A later,
	# separate `eitri setup` run (this test's own second inst call, a fresh process with no
	# override tarball of its own) used to download the real asset from the release server and
	# refuse it as a checksum mismatch -- reading as tampering, when the real reason is that this
	# kind of RELEASE cannot be resolved that way at all.
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_VERDANDI_REPO_URL=$T/verdandi-src" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --checkout "$FS_DIR"
	expect_rc 0
	if ! grep -Fqx 'EITRI_BUILT_FROM_CHECKOUT=1' "$TH/.local/lib/eitri/RELEASE"; then
		fail "the installed RELEASE is not marked EITRI_BUILT_FROM_CHECKOUT: $(cat "$TH/.local/lib/eitri/RELEASE")"
	fi
	# The --checkout install's own run already built (and left present) a sidecar for this rev, from
	# its own override tarball: removed here so the "eitri setup" run below has to actually try to
	# resolve the Verdandi source itself, instead of returning early on "sidecar ... present".
	rm -rf -- "$(data_of)/eitri/sidecar"
	INSTALLER_UNDER_TEST=$TH/.local/lib/eitri/eitri-setup
	sc_inst_setup -- --sidecar-only
	expect_fail "a separate eitri setup run against a checkout-built RELEASE"
	expect_out 'was built from a --checkout tree'
	expect_out 'EITRI_BUILT_FROM_CHECKOUT=1'
	expect_no_out 'checksum mismatch'
	expect_no_out 'tampered'
}

# F4 (v1-dist whole-branch review, 2026-09-28): both tests below used to build most of the way
# through a --from-source run on aarch64 (installer-codex-4's GTK-detection fix and
# installer-codex-5's nvim-offer fix, each real bugs in code only --from-source could reach without
# check_platform's gate). F4 found that the whole attempt was pointless even when those two bugs were
# fixed: fetch_skia_binaries always feeds the one pinned (x86_64) Skia archive, and skia-bindings
# unpacks it with no target check, so a full aarch64 build always failed later anyway, at the link
# step, with a confusing error. do_from_source now refuses up front on any non-x86_64 uname -m
# instead, in both the --checkout and non---checkout shapes below -- moving this file's own aarch64
# coverage to those two refusals. installer-codex-5's own fix is still real code, and its coverage
# moved to test_nvim.sh's t_nvim_offer_mode_aarch64_no_x86_64_nvim_offered, which reaches
# maybe_offer_nvim through --nvim-offer, the one entry point still reachable with no check_platform
# gate. installer-codex-4's fix (lib_dirs_for's own AArch64 ldconfig marker) has no such surviving
# caller: check_platform gates every prebuilt path and do_from_source now gates itself, so there is
# currently no way to reach check_gtk_webkit at all with uname -m reporting non-x86_64. That is the
# Decisions section's own call ("pinning an aarch64 Skia archive is post-v1: nobody here can test an
# ARM build"), not a coverage gap introduced here; lib_dirs_for's aarch64 branch stays in the code,
# ready for whoever pins that archive, but has no reachable test until then.

TESTS="$TESTS t_from_source_non_x86_64_refuses_before_cloning"
t_from_source_non_x86_64_refuses_before_cloning() {
	# The network (non---checkout) shape: refuses even before fetching SHA256SUMS, so a stranger on
	# an unsupported architecture never reaches the x86_64 Skia archive at all.
	srv_mark
	PRE_STUBS=$T/stubs-aarch64uname
	mkdir -p "$PRE_STUBS"
	cp "$FIXTURES/uname-aarch64" "$PRE_STUBS/uname"
	chmod 0755 "$PRE_STUBS/uname"
	inst_net -- --from-source
	expect_fail "--from-source on an unsupported architecture"
	expect_out 'v1 builds x86_64 only, and this is aarch64'
	if [ -n "$(srv_paths)" ]; then fail "the fixture server was reached despite the up-front refusal: $(srv_paths)"; fi
}

TESTS="$TESTS t_from_source_checkout_refuses_on_non_x86_64"
t_from_source_checkout_refuses_on_non_x86_64() {
	# The --checkout (local dev loop) shape: same refusal, before check_build_tools/check_gtk_webkit
	# even run, so a checkout with no cargo/GTK available on this host still gives the clear
	# architecture message rather than a confusing missing-build-tools one.
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_repo 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git ddddddd000000000000000000000000000000000
	PRE_STUBS=$T/stubs-aarch64uname
	mkdir -p "$PRE_STUBS"
	cp "$FIXTURES/uname-aarch64" "$PRE_STUBS/uname"
	chmod 0755 "$PRE_STUBS/uname"
	inst -- --from-source --checkout "$FS_DIR"
	expect_fail "--from-source --checkout on an unsupported architecture"
	expect_out 'v1 builds x86_64 only, and this is aarch64'
	expect_no_out 'GTK 4.14.5 and WebKitGTK 6.0: ok'
	expect_no_out 'build tools: ok'
}

# fs_repo_public VERSION VERDANDI_URL VERDANDI_REV: fs_repo in the PUBLIC tree's shape (publish/export.sh):
# Cargo.lock names no git source for neovide, and neovide/ is a git submodule (a gitlink HEAD records)
# checked out from a small fixture repo. Sets FS_DIR, FS_HEAD and FS_NEOVIDE_HEAD (v1-dist Task 12
# sub-plan Task 5: --from-source --checkout used to die in a public clone for want of that source line).
fs_repo_public() {
	FS_NEOVIDE_SRC=$T/neovide-src
	rm -rf "$FS_NEOVIDE_SRC"
	mkdir -p "$FS_NEOVIDE_SRC"
	printf 'fixture fork\n' >"$FS_NEOVIDE_SRC/README"
	git -C "$FS_NEOVIDE_SRC" init -q
	# shellcheck disable=SC2086
	git -C "$FS_NEOVIDE_SRC" $FS_GIT_ID add -A
	# shellcheck disable=SC2086
	git -C "$FS_NEOVIDE_SRC" $FS_GIT_ID commit -q -m fork-one
	FS_NEOVIDE_HEAD=$(git -C "$FS_NEOVIDE_SRC" rev-parse HEAD)
	FS_DIR=$T/fs-repo
	# fs_scaffold writes a private-shape Cargo.lock from FS_FORK_REV; it is replaced right below.
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_scaffold "$FS_DIR" "$1" "$2" "$3"
	{
		printf '# This file is automatically @generated by Cargo.\nversion = 3\n\n'
		printf '[[package]]\n'
		printf 'name = "neovide"\n'
		printf 'version = "0.1.0"\n'
	} >"$FS_DIR/Cargo.lock"
	git -C "$FS_DIR" init -q
	# shellcheck disable=SC2086
	git -C "$FS_DIR" $FS_GIT_ID -c protocol.file.allow=always submodule add -q "$FS_NEOVIDE_SRC" neovide
	# shellcheck disable=SC2086
	git -C "$FS_DIR" $FS_GIT_ID add -A
	# shellcheck disable=SC2086
	git -C "$FS_DIR" $FS_GIT_ID commit -q -m base
	git -C "$FS_DIR" tag "v$1"
	FS_HEAD=$(git -C "$FS_DIR" rev-parse HEAD)
}

TESTS="$TESTS t_from_source_checkout_public_shape_builds_and_installs"
t_from_source_checkout_public_shape_builds_and_installs() {
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo_public 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_VERDANDI_REPO_URL=$T/verdandi-src" \
		--set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --checkout "$FS_DIR"
	expect_rc 0
	expect_exec "$TH/.local/lib/eitri/shell"
	have_fork=$(sed -n 's/^NEOVIDE_FORK_COMMIT=//p' "$TH/.local/lib/eitri/RELEASE")
	expect_eq "$have_fork" "$FS_NEOVIDE_HEAD" "the synthesized RELEASE's NEOVIDE_FORK_COMMIT (the submodule's gitlink)"
}

TESTS="$TESTS t_from_source_checkout_public_shape_moved_submodule_refuses"
t_from_source_checkout_public_shape_moved_submodule_refuses() {
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo_public 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	# The checkout moves past what HEAD records: the build would compile a fork RELEASE does not name.
	printf 'moved\n' >>"$FS_DIR/neovide/README"
	# shellcheck disable=SC2086
	git -C "$FS_DIR/neovide" $FS_GIT_ID commit -q -am fork-two
	PRE_STUBS=$(fs_cargo_stubs)
	inst -- --from-source --checkout "$FS_DIR"
	expect_rc 1
	expect_out 'submodule update neovide'
	if grep -q '^cargo build ' "$S/logs/cargo.log"; then fail "cargo build ran with the submodule off its recorded commit"; fi
}

TESTS="$TESTS t_from_source_checkout_public_shape_uninitialised_submodule_refuses"
t_from_source_checkout_public_shape_uninitialised_submodule_refuses() {
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo_public 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git "$FS_VC_HEAD"
	git -C "$FS_DIR" submodule deinit -q -f neovide
	PRE_STUBS=$(fs_cargo_stubs)
	inst -- --from-source --checkout "$FS_DIR"
	expect_rc 1
	expect_out 'submodule update --init neovide'
	if grep -q '^cargo build ' "$S/logs/cargo.log"; then fail "cargo build ran with no fork checked out"; fi
}

TESTS="$TESTS t_from_source_checkout_short_rev_refuses"
t_from_source_checkout_short_rev_refuses() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_repo 1.0.0 https://github.com/HunterGrey-cyber/verdandi.git ddddddd
	PRE_STUBS=$(fs_cargo_stubs)
	inst -- --from-source --checkout "$FS_DIR"
	expect_rc 1
	expect_out 'not a full 40-hex commit'
	if grep -q '^cargo build ' "$S/logs/cargo.log"; then fail "cargo build ran despite the short rev"; fi
}

TESTS="$TESTS t_from_source_checkout_private_verdandi_without_checkout_refuses"
t_from_source_checkout_private_verdandi_without_checkout_refuses() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_repo 1.0.0 ssh://git@example.invalid/grey/verdandi.git ddddddd000000000000000000000000000000000
	PRE_STUBS=$(fs_cargo_stubs)
	inst -- --from-source --checkout "$FS_DIR"
	expect_rc 1
	expect_out 'pins Verdandi from a private source'
	expect_out 'EITRI_VERDANDI_CHECKOUT'
	expect_out '--verdandi-checkout'
	if grep -q '^cargo build ' "$S/logs/cargo.log"; then fail "cargo build ran despite the unreachable private source"; fi
}

TESTS="$TESTS t_from_source_checkout_private_verdandi_with_checkout_succeeds"
t_from_source_checkout_private_verdandi_with_checkout_succeeds() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 ssh://git@example.invalid/grey/verdandi.git "$FS_VC_HEAD"
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --checkout "$FS_DIR" --verdandi-checkout "$T/verdandi-src"
	expect_rc 0
	expect_exec "$TH/.local/lib/eitri/shell"
}

# ---------------------------------------------------------------------------------------------
# --verdandi-checkout DIR (DEV-1, spec §6.2)

TESTS="$TESTS t_verdandi_checkout_rev_mismatch_refuses"
t_verdandi_checkout_rev_mismatch_refuses() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	# The Eitri checkout pins a DIFFERENT rev than $T/verdandi-src is actually at.
	fs_repo 1.0.0 ssh://git@example.invalid/grey/verdandi.git ffffffff00000000000000000000000000000000
	PRE_STUBS=$(fs_cargo_stubs)
	inst -- --from-source --checkout "$FS_DIR" --verdandi-checkout "$T/verdandi-src"
	expect_rc 1
	expect_out 'is at'
	expect_out 'not the pinned'
	expect_out 'allow-verdandi-rev-mismatch'
	if grep -q '^cargo build ' "$S/logs/cargo.log"; then fail "cargo build ran despite the rev mismatch"; fi
}

TESTS="$TESTS t_verdandi_checkout_dirty_tree_refuses"
t_verdandi_checkout_dirty_tree_refuses() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 ssh://git@example.invalid/grey/verdandi.git "$FS_VC_HEAD"
	echo 'dirty' >>"$T/verdandi-src/package.json"
	PRE_STUBS=$(fs_cargo_stubs)
	inst -- --from-source --checkout "$FS_DIR" --verdandi-checkout "$T/verdandi-src"
	expect_rc 1
	expect_out 'has modified tracked files'
	if grep -q '^cargo build ' "$S/logs/cargo.log"; then fail "cargo build ran despite the dirty checkout"; fi
}

TESTS="$TESTS t_verdandi_checkout_allow_mismatch_proceeds_and_records"
t_verdandi_checkout_allow_mismatch_proceeds_and_records() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 ssh://git@example.invalid/grey/verdandi.git ffffffff00000000000000000000000000000000
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --checkout "$FS_DIR" --verdandi-checkout "$T/verdandi-src" --allow-verdandi-rev-mismatch
	expect_rc 0
	expect_out 'building against it anyway'
	expect_exec "$TH/.local/lib/eitri/shell"
}

# snap_but_git_index DIR: snap, except .git/index's own mtime and .git's own directory mtime --
# `git status`/`git rev-parse HEAD`/`git archive` legitimately refresh the index's stat cache (so
# its mtime) and transiently create-and-remove a lock file directly under .git/ (so ITS mtime, the
# same reason harness.sh's own snap_but_lock excludes ./.cache and ./.cache/eitri), with no
# content change at all -- comparing either verbatim would fail on the harness's own read-only
# probes, not on anything this installer did.
snap_but_git_index() {
	snap "$1" | sed -E \
		-e 's#^(\./\.git/index f [0-9]+ [0-9]+) [0-9.]+ #\1 - #' \
		-e 's#^(\./\.git d [0-9]+ [0-9]+) [0-9.]+ #\1 - #'
}

TESTS="$TESTS t_verdandi_checkout_archive_leaves_checkout_unchanged"
t_verdandi_checkout_archive_leaves_checkout_unchanged() {
	FS_FORK_REV=eeeeeee111111111111111111111111111111111
	fs_verdandi_checkout "$T/verdandi-src"
	fs_repo 1.0.0 ssh://git@example.invalid/grey/verdandi.git "$FS_VC_HEAD"
	before_status=$(git -C "$T/verdandi-src" status --porcelain)
	before_snap=$(snap_but_git_index "$T/verdandi-src")
	PRE_STUBS=$(fs_cargo_stubs)
	inst --set "EITRI_INSTALL_TEST_NODE_BASE_URL=http://127.0.0.1:$PORT/dist" \
		--set "EITRI_INSTALL_TEST_SKIA_BASE_URL=http://127.0.0.1:$PORT/skia" \
		-- --from-source --checkout "$FS_DIR" --verdandi-checkout "$T/verdandi-src"
	expect_rc 0
	after_status=$(git -C "$T/verdandi-src" status --porcelain)
	after_snap=$(snap_but_git_index "$T/verdandi-src")
	expect_eq "$after_status" "$before_status" "git status of --verdandi-checkout after the build"
	expect_eq "$after_snap" "$before_snap" "the --verdandi-checkout tree's own contents after the build"
}
