[package]
name = "wlr_vptr_drag"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[[bin]]
name = "wlr-vptr-drag"
path = "src/main.rs"

[[bin]]
name = "wlr-vptr-scroll"
path = "src/scroll.rs"

[dependencies]
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
