//! Pins `parse_git_rev_from_lockfile`, the pure text-parsing half of `build.rs`'s `--version`
//! build-identity emission (v1-dist plan Task 1, spec §3). `build.rs` itself is compiled and run
//! as `build-script-build`, never with `--test`, so a `#[cfg(test)]` module written inside it
//! never executes under `cargo test` -- `include!`ing the same source file here, as `build.rs`
//! does, is what makes this parsing logic actually run under the suite. See
//! `../build_info_lockfile.rs`'s own doc comment.

include!("../build_info_lockfile.rs");

// The two git sources use neutral hosts, not the private ones this repo pins: this file ships in the
// public tree (publish/manifest.txt `include shell/*`), and publish/scan.sh rejects a private host
// and any `user@host` outside `example.com`/`.org`/`.net`. The parser reads only the text after the
// last `#`, so the host is irrelevant to it; one `git+ssh://` (the private tree's shape) and one
// `git+https://` (the public tree's) keep both shapes covered.
const LOCKFILE_FIXTURE: &str = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "anyhow"
version = "1.0.100"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "some-checksum-value"

[[package]]
name = "neovide"
version = "0.16.2"
source = "git+ssh://git@example.com/neovide.git?rev=3f1c9a7d24e8b06c5d97e2a41b8f03c6e5d2a917#3f1c9a7d24e8b06c5d97e2a41b8f03c6e5d2a917"
dependencies = [
 "anyhow",
]

[[package]]
name = "claude-runtime-protocol"
version = "0.1.0"
source = "git+https://example.invalid/verdandi.git?rev=a4d82e6#a4d82e6f0b19c73e58f2d4a60c9b7e13f5a82c04"
dependencies = [
 "prost",
]

[[package]]
name = "shell"
version = "1.0.0-rc.1"
dependencies = [
 "agent",
]
"#;

#[test]
fn finds_the_full_sha_after_the_last_hash_in_a_git_source_line() {
    assert_eq!(
        parse_git_rev_from_lockfile(LOCKFILE_FIXTURE, "neovide"),
        Some("3f1c9a7d24e8b06c5d97e2a41b8f03c6e5d2a917".to_string())
    );
    assert_eq!(
        parse_git_rev_from_lockfile(LOCKFILE_FIXTURE, "claude-runtime-protocol"),
        Some("a4d82e6f0b19c73e58f2d4a60c9b7e13f5a82c04".to_string())
    );
}

#[test]
fn a_path_dependency_with_no_source_line_is_none_not_a_panic() {
    // `shell` itself has no `source` line (a workspace member) -- this is the exact shape a
    // path-dependency `neovide/` submodule in the public tree would have too.
    assert_eq!(parse_git_rev_from_lockfile(LOCKFILE_FIXTURE, "shell"), None);
}

#[test]
fn an_unknown_package_name_is_none() {
    assert_eq!(parse_git_rev_from_lockfile(LOCKFILE_FIXTURE, "does-not-exist"), None);
}

#[test]
fn an_empty_lockfile_is_none_not_a_panic() {
    assert_eq!(parse_git_rev_from_lockfile("", "neovide"), None);
}

/// The public tree's lockfile: `neovide` is a path dependency, so it has no `source` line.
const PATH_NEOVIDE_LOCKFILE: &str = "version = 4\n\n[[package]]\nname = \"neovide\"\nversion = \"0.16.2\"\n";

#[test]
fn the_fork_rev_is_the_lockfiles_where_it_has_one_whatever_the_override_says() {
    let rev = resolve_fork_rev(LOCKFILE_FIXTURE, Some("1".repeat(40)), || Some("2".repeat(40)));
    assert_eq!(rev, Some("3f1c9a7d24e8b06c5d97e2a41b8f03c6e5d2a917".to_string()));
}

#[test]
fn a_path_neovide_takes_the_override_before_its_checkout() {
    // Whole-branch review (lane D): the source asset has no `.git` in `neovide/`, so an offline
    // rebuild from it said "neovide fork unknown" where the shipped binary names the fork commit.
    // `SOURCE` now gives `NEOVIBE_BUILD_FORK_COMMIT`, and it must win over asking git.
    let mut asked_git = false;
    let rev = resolve_fork_rev(PATH_NEOVIDE_LOCKFILE, Some("1".repeat(40)), || {
        asked_git = true;
        Some("2".repeat(40))
    });
    assert_eq!(rev, Some("1".repeat(40)));
    assert!(!asked_git);
}

#[test]
fn a_path_neovide_with_no_or_an_empty_override_asks_its_checkout() {
    for unset in [None, Some(String::new())] {
        assert_eq!(
            resolve_fork_rev(PATH_NEOVIDE_LOCKFILE, unset, || Some("2".repeat(40))),
            Some("2".repeat(40))
        );
    }
    assert_eq!(resolve_fork_rev(PATH_NEOVIDE_LOCKFILE, None, || None), None);
}
